version: "3.9"
services:
  pg_db:
    image: postgres
    container_name: pg_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=vardb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data:
    driver: local
