version: "3.9"
services:
  pg_db:
    image: postgres
    container_name: pg_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=vardb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  sonarqube:
    image: docker.io/bitnami/sonarqube
    ports:
      - '9000:9000'
    volumes:
      - sonarqube_data:/bitnami/sonarqube
    environment:
      - SONARQUBE_DATABASE_HOST=rpi.local
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=root
      - SONARQUBE_DATABASE_PASSWORD=root
      - SONARQUBE_DATABASE_NAME=vardb

volumes:
  postgres_data:
    driver: local
  sonarqube_data:
    driver: local
